### ISSUE TITLE
Illegal transitions correction fails when noface or nobaby face is replaced with left, right or away

### ISSUE THREAD

**Issue by GalRaz** [icatcherplus/icatcher_plus#34]
example video shared securely.

**Comment by yoterel** [comment]
Just to give context, illegal transitions is an option for post-processing results from icatcher, to abide certain human made rules for the output. For example a user might want to swap any transition such as "left, right, left" with "left, left, left", since it might be physically impossible to transition that quickly from left to right.

The naive way to solve would be the perform a 2nd pass over the full output, and fixing all user defined illegal transition rules.

The current implementation does not do this, but rather buffers the output and replaces illegal transitions on the fly. The reason swapping any negative classes (no face) with positive ones fail is we don't currently update the bounding boxes used for visualization, so if someone wants to see the result or save to disk an output video it fails.

**Comment by yoterel** [comment]
fixed with #37
