### ISSUE TITLE
Issue with a particular video from Lookit terminating prematurely without any frame annotations 

### ISSUE THREAD

**Issue by GalRaz** [icatcherplus/icatcher_plus#35]
Video has been shared securely.

**Comment by yoterel** [comment]
The problem was with the video file itself, having some structural problem when created.
Strictly following the video format, the only real solution is to create a proper video.
However ffmpeg can "buffer lookahead" and try to solve the problem by caching frames of the video, which is what "-max_muxing_queue_size" does. I pushed a fix to do this, but this might cause machine to run out of memory in some rare cases (though for the file shared this works).

[more info](https://stackoverflow.com/questions/49686244/ffmpeg-too-many-packets-buffered-for-output-stream-01)
