### ISSUE TITLE
Fix hard coded values

### ISSUE THREAD

**Issue by AminSarafraz** [icatcherplus/icatcher_plus#59]
Based on our discussion, the following values are hard coded, fixing it will help with training using other datasets

```
reproduce/models.py line 314
    self.fc3 = torch.nn.Linear(512, 3)

reproduce/preprocess.py line 467
    classes = {"away": 0, "left": 1, "right": 2}

reproduce/preprocess.py line 625
    classes = {"away": 0, "left": 1, "right": 2}

```

**Comment by yoterel** [comment]
For now, I decided to leave this untouched as the reproduce folder is used to replicate results rather than allowing extensions. Anyone wanting to retrain will need to manually step through the code anyway, and this comment might serve as a hint as to what needs changing for a 4 class (or more) training.
